initial_state: q0

accepting_states:
- q0
- q1
- q2
- q3
- q4
- q5
- q6
- q7
- q8
- q9

transitions:
  q0:
    a: q1
    b: q2
    c: q3
    d: q4
    e: q5
    f: q6
    g: q7
    h: q8
    i: q9
  q1:
    a: q0
  q2:
    b: q0
  q3:
    c: q0
  q4:
    d: q0
  q5:
    e: q0
  q6:
    f: q0
  q7:
    g: q0
  q8:
    h: q0
  q9:
    i: q0

states_set:
- q0
- q1
- q2
- q3
- q4
- q5
- q6
- q7
- q8
- q9

character_set:
- a
- b
- c
- d
- e
- f
- g
- h
- i
- j
- k
- l
- m
- n
- o
- p
- q
- r
- s
- t
- u
- v
- w
- x
- y
- z
