initial_state: q0

accepting_states:
- q0
- q1
- q2
- q3
- q4
- q5

transitions:
  q0:
    a: q1
    b: q2
    c: q3
    d: q4
    e: q5
  q1:
    a: q0
  q2:
    b: q0
  q3:
    c: q0
  q4:
    d: q0
  q5:
    e: q0

states_set:
- q0
- q1
- q2
- q3
- q4
- q5

character_set:
- a
- b
- c
- d
- e
